"""Vocabulary and trust policy shared by author metadata inference."""


HEADING_STOPWORDS = {
    "chapter",
    "part",
    "book",
    "section",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "ten",
    "the",
    "and",
    "of",
    "to",
    "in",
    "for",
    "on",
    "with",
    "from",
    "at",
    "against",
    "a",
    "an",
}


AUTHOR_ROLE_HINTS = {
    "author",
    "authors",
    "editor",
    "editors",
    "writer",
    "writers",
    "by",
    "written by",
    "edited by",
    "text by",
    "article by",
    "essay by",
}


AUTHOR_STOP_TERMS = {
    "chapter",
    "contents",
    "copyright",
    "preface",
    "foreword",
    "introduction",
    "conclusion",
    "notes",
    "bibliography",
    "index",
    "university press",
    "press books",
    "duke university press",
    "yale university press",
    "oxford university press",
    "acknowledgments",
    "acknowledgements",
    "paperback edition",
    "view crossmark data",
    "article views",
    "view related articles",
    "submit your article",
    "to cite this article",
    "to link to this article",
    "full terms conditions of access and use",
    "stable url",
    "published by",
    "journal homepage",
    "proquest ebook central",
    "jstor",
    "terms conditions of use",
    "syllabus",
    "reviewed work",
    "creative commons",
    "noncommercial",
    "license",
}


AUTHOR_BLOCK_STOP_HINTS = {
    "abstract",
    "introduction",
    "keywords",
    "contents",
    "table of contents",
    "to cite this article",
    "to link to this article",
    "published online",
    "submit your article",
    "article views",
    "view related articles",
    "view crossmark data",
    "full terms",
    "journal homepage",
    "issn:",
    "doi:",
    "stable url",
    "published by",
    "source:",
    "jstor",
    "proquest ebook central",
    "instructor:",
}


AUTHOR_NAME_PARTICLES = {
    "al",
    "bin",
    "da",
    "de",
    "del",
    "den",
    "der",
    "di",
    "du",
    "el",
    "la",
    "le",
    "ten",
    "van",
    "von",
}


AUTHOR_AFFILIATION_HINTS = {
    "university",
    "universidad",
    "universidade",
    "universita",
    "università",
    "universitat",
    "universität",
    "universite",
    "université",
    "unibertsitatea",
    "institute",
    "school",
    "department",
    "college",
    "laboratory",
    "lab",
    "research",
    "researcher",
    "google",
    "facebook",
    "microsoft",
    "openai",
    "anthropic",
    "amazon",
    "meta",
    "tech",
}


POST_EXTRACTION_AUTHOR_TRUSTED_SOURCES = {
    "text_thesis_titlepage_author",
    "text_corporate_cover_byline",
    "text_byline",
    "text_written_by",
    "text_edited_by",
    "text_review_byline",
    "text_column_byline",
    "text_author_label",
    "text_writer_label",
    "text_bibliographic_author_label",
    "text_instructor_label",
    "text_affiliated_byline",
    "text_adjacent_affiliated_byline",
    "text_explicit_multi_author_byline",
    "text_title_window_adjacent_byline",
    "text_visible_title_person_prefix",
    "text_opening_title_block_byline",
    "text_strict_credit_block",
    "text_stacked_affiliated_byline",
    "text_bibliographic_byline",
    "text_compact_caps_byline",
}


TRUSTED_AUTHOR_INFERENCE_SOURCES = POST_EXTRACTION_AUTHOR_TRUSTED_SOURCES | {
    "text_medical_multicolumn_byline",
    "text_repository_cover_correlated_byline",
    "text_editorial_end_signature",
    "text_review_affiliated_byline",
    "text_dated_opening_byline",
    "text_report_prepared_by",
    # Native PDF title geometry is sufficiently strong for catalog metadata,
    # but OCR can hallucinate the same adjacency. Keep it out of the stricter
    # post-OCR mutation allowlist above.
    "text_title_adjacent_byline",
    "text_titlepage_publisher_byline",
    "text_title_byline_translation",
    "text_first_lines_stacked_byline",
    "text_role_followup",
    "filename_explicit_byline",
    "filename_leading_name",
    "filename_leading_names",
    "filename_leading_surname",
    "filename_leading_name_before_section",
    "filename_corroborated_text_name",
    "filename_leading_surnames",
    "filename_compact_name_before_year",
    "filename_name_before_section_label",
    "filename_surname_before_year",
    "filename_surname_before_section_number",
    "filename_structured_corroborated_text_names",
}


AUTHOR_ORGANIZATION_TERMS = {
    "academy",
    "association",
    "affiliated",
    "board",
    "center",
    "centre",
    "church",
    "college",
    "committee",
    "department",
    "desk",
    "faculty",
    "foundation",
    "inc",
    "institute",
    "journal",
    "laboratory",
    "llc",
    "ltd",
    "office",
    "news",
    "press",
    "publisher",
    "repository",
    "school",
    "society",
    "systems",
    "university",
    "universidad",
    "universidade",
    "universita",
    "università",
    "universitat",
    "universität",
    "universite",
    "université",
    "unibertsitatea",
}


AUTHOR_NON_PERSON_BYLINE_TERMS = {
    "editorial board",
    "newsroom",
    "the associated press",
    "associated press",
    "reuters",
    "staff report",
    "staff reports",
}
